version: '3.7'
services:
    lunch:
        init: true
        ports:
            - '8080:80'
        environment:
            - TITLE=${TITLE:-Backend}
            - COLOR=${COLOR:-lightgreen}
        image: 'lunch:v6'